In [1]:
import numpy as np
import cv2 as cv
import face_recognition as fc
import os

In [2]:
path = "/Users/admin/Documents/MyDocuments/Ai/DeepLearning/DeepLearning Courses/Ostad Ghasemi/Codes/Face Recognition-With-CV2/Validatio Soorat"
images = []
classNames = []

In [3]:
myList = os.listdir(path)
myList.remove('.DS_Store')
for cl in myList:
    curImg = cv.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print (classNames)

['Masood', 'Mojtaba', 'Behzad', 'Vahid']


In [4]:
def findEncodings(images):

    encodeList = []
    for img in images:
        img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
        encode = fc.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

In [5]:
encodelistKnown = findEncodings(images)
print ("Encodine Complete")

Encodine Complete


In [6]:
print (len(encodelistKnown))

4


In [11]:
cap = cv.VideoCapture(0)

while True:

    success, img = cap.read()
    imgS = cv.resize(img,(0,0),None,0.25,0.25)
    imgS = cv.cvtColor(imgS, cv.COLOR_BGR2RGB)

    faceCurFrame = fc.face_locations(imgS)
    encodeCurFrame = fc.face_encodings(imgS, faceCurFrame)

    for encodeFace,faceloc in zip(encodeCurFrame,faceCurFrame):
        matches = fc.compare_faces(encodelistKnown,encodeFace)
        faceDis = fc.face_distance(encodelistKnown,encodeFace)
        print (faceDis)

        matchIndex = np.argmin(faceDis)
        print (matchIndex)

        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print (name)
            y1,x2,y2,x1 = faceloc
            y1,x2,y2,x1 = y1*4,x2*4,y2*4,x1*4
            cv.rectangle(img, (x1, y1),(x2,y2),(0,255,0) ,2)
            cv.rectangle(img, (x1,y2-55),(x2,y2),(0,255,0), cv.FILLED)
            cv.putText (img, name, (x1+5,y2-5), cv.FONT_HERSHEY_SIMPLEX, 2, (0,0,255),5)

    cv.imshow('Webcam', img)
    cv.waitKey(1)

    

[0.65532749 0.77130327 0.59901623 0.62470518]
2
BEHZAD
[0.6969973  0.79002064 0.64268854 0.63117007]
3
[0.66675355 0.77082243 0.62768034 0.68693304]
2
[0.68766527 0.77207242 0.58934695 0.63122298]
2
BEHZAD
[0.66816468 0.793216   0.6125356  0.68911164]
2
[0.68347769 0.80229004 0.59315835 0.68494088]
2
BEHZAD
[0.7385285  0.8191646  0.59393891 0.70985208]
2
BEHZAD
[0.74539884 0.81225278 0.622674   0.75151412]
2
[0.72046283 0.80802699 0.6295103  0.73771016]
2
[0.68418757 0.78441627 0.64316407 0.69497885]
2
[0.72130945 0.80986824 0.65127692 0.75200845]
2
[0.69639368 0.79957168 0.66512818 0.73087431]
2
[0.72068204 0.80729961 0.61688718 0.72141905]
2
[0.71217822 0.78791024 0.6502308  0.72057503]
2
[0.69930105 0.78925852 0.63390397 0.75232963]
2
[0.68188112 0.79404351 0.62983587 0.72099877]
2
[0.68007147 0.78336227 0.61867876 0.69757314]
2
[0.64287636 0.7463409  0.63064199 0.68445774]
2
[0.61100549 0.73886355 0.65004275 0.70903767]
0
[0.67490961 0.78067044 0.66919409 0.78368199]
2
[0.64392476 

KeyboardInterrupt: 